account/urls.py
from django.urls import path
from . import views

app_name='account'


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user,name='login_user'),
    path('logout/',views.logout_user, name='logout_user'),
    path('create_admin/',views.create_admin,name='create_admin'),
    path('edit-user/<int:id>', views.edit_user, name='edit_user'),
    path('change-password', views.change_password, name='change_password'),
    path('change-password-admin/<int:id>',views.admin_can_change_password, name='admin_can_change_password'),
  
]

helloprasashan/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth import views as auth_views
from account.views import CustomPasswordResetView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls', namespace='main')),
    path('account/',include('account.urls', namespace='account')),
    path('social-auth/',include('social_django.urls', namespace='social')),

    path(
        "reset-password/",
        CustomPasswordResetView.as_view(
            template_name="account/forget-password.html"
        ),
        name="reset_password",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name='account/password_reset_done.html'
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/reset_password.html"
        ),
        name='password_reset_confirm',
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name='account/password_reset_complete.html'
        ),
        name="password_reset_complete",
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name='main'


urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('dashboard/', views.dashboard,name='dashboard'),
    path('dashboard/', views.dashboard,name='dashboard'),
    path('create_complain', views.create_complain,name='create_complain'),
    path('profile_details',views.my_account,name='my_account'),
    path('view_complain/<int:id>', views.view_complain, name='view_complain'),
    path('view_response/<int:id>', views.view_response, name='view_response'),
    path('all_complain', views.all_complain, name='all_complains'),
    path('add_category', views.add_category, name='add_category'),
    path('view_category', views.view_category,name='view_category'),
    path('anonymous_complain', views.anonymous_complain, name='anonymous_complains'),
    path('all_user', views.all_user, name='all_user'),
    path('all_user/view_user/<int:id>',views.view_user,name='view_user'),
    path('delete_user/<int:id>',views.delete_user,name='delete_user'),
    path('complain_responses', views.complain_responses, name='complain_responses'),
    path('anonymous_form', views.anonymous_form, name="anonymous_form"),
    path("aboutus/", views.AboutUs, name='about'),
    path('privacy/',views.privacy,name='privacy'),
    path('faq/',views.faq,name='faq'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from . import choices

from main.models import ComplainName


class CustomUser(AbstractUser):
    username = models.CharField(max_length=255,unique=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(
        max_length=10, null=True, 
        validators=[
            RegexValidator(r'^\d{10}$', 'Phone number must be 10 digits')
        ]
    )
    created_date=models.DateTimeField(auto_now_add=True)
    role = models.PositiveSmallIntegerField(
        choices=choices.ROLE_CHOICES, blank=True, default=3
    )
    admin_category = models.ForeignKey(
        ComplainName, on_delete=models.SET_NULL, null=True
    )
    
    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['username',]
    
    def __str__(self) -> str:
        return self.email
    
    def role_name(self):
        if self.role==1:
            return 'superadmin'
        elif self.role==2:
            return 'admin'
        else:
            return 'user'
   
    # list_display = ["email",'first_name','last_name', "username",]

main/models.py
from django.db import models
from django.conf import settings


class Complain(models.Model):
    created_by=models.ForeignKey(settings.AUTH_USER_MODEL, related_name='my_complains', on_delete=models.CASCADE,default=None,null=True)
    created_date=models.DateTimeField(auto_now_add=True)
    complain_title=models.CharField(max_length=255,null=False)
    complain_message=models.TextField(null=False)
    complain_image=models.ImageField(null=True, upload_to="Images")
    to_complain=models.ForeignKey('ComplainName', on_delete=models.CASCADE)
    class Meta:
        ordering=['-created_date']

    def __str__(self):
        return self.complain_title
    
    
    
class ComplainName(models.Model):
    department_name = models.CharField(max_length=255,null=False)
    complain_name = models.CharField(max_length=255,null=False)

    def __str__(self):
        return self.complain_name
    
#Response Model
class Response(models.Model):
    response_to=models.OneToOneField(Complain, related_name="response", on_delete=models.CASCADE,default=None,null=True)
    response_by=models.ForeignKey(settings.AUTH_USER_MODEL, related_name="responses",on_delete=models.CASCADE,null=True,default=None)
    response_body=models.TextField()
    response_image=models.ImageField(null=True,upload_to="Images")
    created_date=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=['-created_date']

main/forms.py
from django import forms

from .models import Complain


class ComplainForm(forms.ModelForm):
    """Form for validating Complain."""
    complain_image = forms.ImageField(required=False)
    class Meta:
        model = Complain
        fields = ['complain_title', 'complain_message', 'complain_image', 'to_complain']


class ComplainSearch(forms.ModelForm):
    search_title=forms.CharField(required=False)
    from_date=forms.DateTimeField(required=False)
    to_date=forms.DateTimeField(required=False)

class UserSearch(forms.ModelForm):
    Search_titile=forms.CharField(required='False')

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from account.models import CustomUser
from account.decorators import is_admin,is_superadmin,is_user
from django.contrib.auth.decorators import login_required,user_passes_test
from django.utils import timezone
from django.contrib import messages
from datetime import datetime
from django.db.models import Q
from . models import Complain, ComplainName, Response
from django.db.models import Count
from .forms import ComplainForm
from account import choices

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return dashboard(request)
    return render(request, 'main/index.html')

@login_required
def dashboard(request):
    return render(request,'main/dashboard.html')
#View category Function
@is_superadmin
def view_category(request):
    categories=ComplainName.objects.all()
    context={
        'categories':categories
    }
    return render(request,'main/view_category.html',context)
# View to add new Complain Category
@is_superadmin
def add_category(request):
    if request.method=="POST":
        complain_department=request.POST.get('complain_department')
        complain_category=request.POST.get('complain_category')
        ComplainName.objects.create(
            department_name=complain_department,
            complain_name=complain_category,

        )
        return redirect(reverse('main:view_category'))
    return render(request,'main/add_category.html')


@is_user
def create_complain(request):
    """For creating complains."""
    complain_name = ComplainName.objects.all()
    if request.method == 'POST':
        form = ComplainForm(request.POST, request.FILES)
        if form.is_valid():
            complain = form.save(commit=False)
            complain.created_by = request.user
            complain.save()
            return redirect(reverse('main:all_complains'))
        else:
            messages.info(request, f'Please select Complain Category')
            return redirect(reverse('main:create_complain'))
    
    context = {'complain_name':complain_name}

    return render(request, 'main/create-complain.html', context)


#viewing individual Complain
def view_complain(request, id):
    complain=get_object_or_404(Complain, id=id)
    context={
        'complain':complain
    }
    if request.method=="POST":
        response_body=request.POST.get("response_body")
        response_image = request.FILES.get("response_image")
        Response.objects.create(
            response_by=request.user,
            response_to_id=complain.id,
            response_body=response_body,
            response_image=response_image,
        )
        return redirect("main:view_complain", id=complain.id)
    return render(request,'main/view_complain.html',context)


#view for all complains for admin and superadmin
def all_complain(request):
    user=request.user
    search_title = request.GET.get('search_title', '')
    from_date = request.GET.get('from_date', '')
    to_date = request.GET.get('to_date', '')
    reset_button = request.GET.get('reset_button', '')
    if user.role == 1:
        complains=Complain.objects.filter(
            created_by__isnull= False
        ).annotate(response_count = Count('response'))
        complains = complains.filter(response_count = 0)

    elif user.role == 2:
        complains=Complain.objects.filter(
            Q(to_complain__department_name = user.admin_category.department_name) & 
            Q(created_by__isnull= False)
        ).annotate(response_count = Count('response'))
        complains = complains.filter(response_count = 0)
    else:
        my_complains=Complain.objects.filter(created_by=user).annotate(response_count=Count('response'))
        complains=my_complains.filter(response_count=0)
    if reset_button:
        pass
    else:
        if search_title:
            complains = complains.filter(
                Q(complain_title__icontains=search_title) |
                Q(complain_message__icontains=search_title)
            )
        if from_date:
            complains = complains.filter(created_date__gte=from_date)
        if to_date:
            complains = complains.filter(created_date__lte=to_date)
    context={
        'complains' :complains,
    }
    return render(request,'main/all_complains.html',context)



# Complain_responses
def complain_responses(request):
    user=request.user
    search_title = request.GET.get('search_title', '')
    from_date = request.GET.get('from_date', '')
    to_date = request.GET.get('to_date', '')
    reset_button = request.GET.get('reset_button', '')
    if user.role == 1:
        responses=Response.objects.all()
    elif user.role == 2:
        responses=user.responses.all()
    else:
        my_complains=user.my_complains.all()
        responses=Response.objects.filter(response_to__in=my_complains)

    

    if search_title:
        responses = responses.filter(
            Q(response_body__icontains = search_title) |
            Q(response_to__complain_title__icontains = search_title) |
            Q(response_to__complain_message__icontains=search_title)
        )
    if from_date:
        responses = responses.filter(created_date__gte=from_date)
    if to_date:
        responses = responses.filter(created_date__lte=to_date)
    context={
        'responses': responses
    }
    return render(request, 'main/responses.html', context)

def view_response(request, id):
    complain=get_object_or_404(Complain, id=id)
    context={
        'complain':complain
    }
    return render(request,'main/view_response.html',context)


@is_superadmin
def all_user(request):
    users=CustomUser.objects.all()
    roles=choices.ROLE_CHOICES
    search_title = request.GET.get('search_title', '')
    role = request.GET.get('role', '')
    if search_title:
        users=users.filter(
            Q(first_name__icontains=search_title) |
            Q(last_name__icontains = search_title) |
            Q(phone_number__icontains = search_title) |
            Q(email__icontains = search_title) 
        )
    if role:
        users=users.filter(role = role)
    
    context={
        'roles':roles,
        'users':users,
    }
    return render(request, 'main/all_user.html',context)
@is_superadmin
def view_user(request,id):
    user=get_object_or_404(CustomUser, id=id)
    context={
        'user':user,
    }
    return render(request,'main/view_user.html',context)


@is_superadmin
def delete_user(request,id):
    user=get_object_or_404(CustomUser, id=id)
    user.delete()
    return redirect('main:all_user')


def my_account(request):
    return render(request,'main/myaccount.html')


#Anonymous Complain /limiting anonymous user to have maximum of 2 complains
def anonymous_form(request):
    complain_name = ComplainName.objects.all()
    context = {'complain_name':complain_name}
    complaints_today = request.session.get('complaints_today', [])
    if len(complaints_today) >= 2:
        return redirect(reverse('main:index'))
    if request.method == 'POST':
        form = ComplainForm(request.POST, request.FILES)
        if form.is_valid():
            complain = form.save(commit=False)
            complain.save()
            current_date_str = datetime.now().date().isoformat()
            complaints_today.append(current_date_str)
            request.session['complaints_today'] = complaints_today
            request.session.save() 
        return redirect(reverse('main:index'))
    return render(request,'main/anonymous_form.html',context)

#views for anonymous Complains
def anonymous_complain(request):
    user=request.user
    search_title = request.GET.get('search_title', '')
    print(search_title)
    from_date = request.GET.get('from_date', '')
    to_date = request.GET.get('to_date', '')
    if user.role == 1:
        complains=Complain.objects.filter(created_by__isnull= True)
    if search_title:
            complains = complains.filter(
                Q(complain_title__icontains=search_title) |
                Q(complain_message__icontains=search_title)
            )
    if from_date:
        complains = complains.filter(created_date__gte=from_date)
    if to_date:
        complains = complains.filter(created_date__lte=to_date)
    context={
        'anonymous_complains':complains
    }
    return render(request,'main/anonymous_complains.html',context)

#View for responding to the complain

def AboutUs(request):
    context={}
    return render(request,'main/aboutus.html',context)


def privacy(request):
    context={}
    return render(request,'main/privacy.html')

def faq(request):
    return render(request,'main/FAQ.html')

main/templates/main/all_user.html
<!-- My Users Dashoboard -->
{% load static %}
{% include 'layouts/header.html' %}

<section id="dashboard">
  <div class="container-fluid">
    <div class="row">

      <div class="col-md-2">
        {% include 'layouts/left-dash.html' %}
      </div>
  
      <div class="col-md-10 arrange-complain">
        <div class="mid-complain ">

          <div class="mid-complain-heading">
            <div class="dash-header">
              <a href="#" id="back-button">
              <div class="pointer">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                  fill="none">
                  <path
                  d="M13.7369 17.5254C13.6332 17.5256 13.5305 17.5052 13.4347 17.4655C13.3388 17.4259 13.2518 17.3677 13.1786 17.2942L8.44174 12.5574C8.29379 12.4092 8.21069 12.2084 8.21069 11.9991C8.21069 11.7897 8.29379 11.5889 8.44174 11.4408L13.1786 6.70392C13.3266 6.55584 13.5275 6.47266 13.7369 6.47266C13.9463 6.47266 14.1471 6.55584 14.2952 6.70392C14.4433 6.85199 14.5265 7.05282 14.5265 7.26223C14.5265 7.47164 14.4433 7.67248 14.2952 7.82055L10.1167 11.9997L14.2952 16.1776C14.4056 16.288 14.4809 16.4287 14.5113 16.5819C14.5418 16.735 14.5262 16.8938 14.4664 17.0381C14.4066 17.1823 14.3054 17.3056 14.1756 17.3924C14.0457 17.4791 13.8931 17.5254 13.7369 17.5254Z"
                  fill="black" />
                </svg>
              </div>
              </a>
              <div class="heading">
                <p>Users</p>
              </div>
            </div>

            <div class="view-complain">
              <button><a href="{% url 'account:create_admin' %}">Create User</a></button>
            </div>
          </div>

          <div class="mycomplain-content">
            <form method="get" action="{% url 'main:all_user' %}">
            <div class="search-bar">
              <div class="search">
                <div class="search-inner">
                  <svg xmlns="http://www.w3.org/2000/svg" width="21" height="22" viewBox="0 0 21 22"
                    fill="none">
                    <circle cx="9.76657" cy="10.2666" r="8.98856" stroke="black" stroke-width="1.5"
                    stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M16.0183 16.9851L19.5423 20.5" stroke="black" stroke-width="1.5"
                    stroke-linecap="round" stroke-linejoin="round" />
                  </svg>
                  <input type="text" placeholder="Search by Name, Email, Phone No." name='search_title'>
                </div>
              </div>

              <div class="complain-dates">
              <select class="form-select form-control" aria-label="Default select example" name='role'>
                <option selected disabled>Select Role</option>
                {% for k , v in roles %}
                <option value="{{ k }}">{{ v }}</option>
                {% endfor %}
              </select>
            </div>

              <div class="searchbar-button">
                <button>Reset</button>
              </div>

              <div class="searchbar-button">
                <button>Search</button>
              </div>
            </div>
          </form>

            <div class="complain-lowerinfo">

              <table>
                <tr>
                  <th class="serial-head"> <p>S.NO.</p> </th>
                  <th class="complain-head"> <p>FULL NAME</p> </th>
                  <th class="complain-head"> <p>EMAIL ADDRESS</p> </th>
                  <th class="date-list-head"> <p>PHONE NUMBER</p> </th>
                  <th class="complain-head"> <p>USER CATEGORY</p> </th>
                  <th class="date-list-head"> <p>RESGISTER DATE</p> </th>
                  <th class="action-head"> <p>ACTION</p> </th>
                </tr>
                {% for user in users %}
                <tr>
                  <td class="serial-list">{{ user.id }}</td>
                  <td class="complain-title-list"><p>{{user.first_name }} {{ user.last_name }}</p></td>
                  <td class="complain-title-list">
                    <p>{{ user.email }}</p>
                  </td>
                  <td class="date-list-body">
                    <p>{{ user.phone_number}}</p>
                  </td>
                  <td class="complain-title-list">
                    <p>{{ user.role_name }}</p>
                  </td>
                  <td class="date-list-body">
                    <p>{{ user.created_date|date:"Y-M-d" }}</p>
                  </td>
                  <td class="action-body">
                    <div class="action-body-view">
                        <button>
                            <a href="{% url 'main:view_user' id=user.id %}">View</a>
                        </button>
                    </div>
                    <div class="action-body-edit">
                        <button>
                            <a href="{% url 'account:edit_user' id=user.id %}">Edit</a>
                        </button>
                    </div>
                 
                  
                    <div class="action-body-delete">
                        <div class="delete-icon">
                          
                            <a type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop{{user.id}}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="19" height="21"
                                    viewBox="0 0 19 21" fill="none">
                                    <path
                                        d="M16.3249 7.96826C16.3249 7.96826 15.7819 14.7033 15.4669 17.5403C15.3169 18.8953 14.4799 19.6893 13.1089 19.7143C10.4999 19.7613 7.8879 19.7643 5.2799 19.7093C3.9609 19.6823 3.1379 18.8783 2.9909 17.5473C2.6739 14.6853 2.1339 7.96826 2.1339 7.96826"
                                        stroke="#FD371F" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round" />
                                    <path d="M17.7082 4.73975H0.750198" stroke="#FD371F"
                                        stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round" />
                                    <path
                                        d="M14.4406 4.73973C13.6556 4.73973 12.9796 4.18473 12.8256 3.41573L12.5826 2.19973C12.4326 1.63873 11.9246 1.25073 11.3456 1.25073H7.11259C6.53359 1.25073 6.02559 1.63873 5.87559 2.19973L5.63259 3.41573C5.47859 4.18473 4.80259 4.73973 4.01759 4.73973"
                                        stroke="#FD371F" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round" />
                                </svg>
                              </a>
                        </div>
                    </div>

                    
                </td>

                </tr>
                <div class="modal  fade" id="staticBackdrop{{user.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">Delete User</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        Are you sure to delete?
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <a href="{% url 'main:delete_user' id=user.id %}"><button type="button" class="btn btn-danger">Yes</button></a>
                      </div>
                    </div>
                  </div>
                </div>
                
                {% endfor %}
              </table>                     
            </div>
          </div>
        </div>
      </div>

    

    </div>

   

  </div>



</section>





{% include 'layouts/footer.html' %}

main/templates/main/index.html
{% load static %}
{% include 'layouts/header.html' %}
{% include 'layouts/navbar.html' %}
{% include 'layouts/main-content.html' %}
{% include 'layouts/home-footer.html' %}
{% include 'layouts/footer.html' %}

main/templates/main/myaccount.html
<!-- My account Dashoboard -->
{% include 'layouts/header.html' %}

<section id="dashboard">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                
                {% include 'layouts/left-dash.html' %}
            

            </div>
            <div class="col-md-10 arrange-account">
                <div class="mid-complain">
                    <div class="mid-complain-heading">
                        <div class="dash-header">
                            <a href="#" id="back-button">
                            <div class="pointer">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none">
                                    <path
                                        d="M13.7369 17.5254C13.6332 17.5256 13.5305 17.5052 13.4347 17.4655C13.3388 17.4259 13.2518 17.3677 13.1786 17.2942L8.44174 12.5574C8.29379 12.4092 8.21069 12.2084 8.21069 11.9991C8.21069 11.7897 8.29379 11.5889 8.44174 11.4408L13.1786 6.70392C13.3266 6.55584 13.5275 6.47266 13.7369 6.47266C13.9463 6.47266 14.1471 6.55584 14.2952 6.70392C14.4433 6.85199 14.5265 7.05282 14.5265 7.26223C14.5265 7.47164 14.4433 7.67248 14.2952 7.82055L10.1167 11.9997L14.2952 16.1776C14.4056 16.288 14.4809 16.4287 14.5113 16.5819C14.5418 16.735 14.5262 16.8938 14.4664 17.0381C14.4066 17.1823 14.3054 17.3056 14.1756 17.3924C14.0457 17.4791 13.8931 17.5254 13.7369 17.5254Z"
                                        fill="black" />
                                </svg>
                            </div></a>
                            <div class="heading">
                                <p>My Account</p>
                            </div>
                        </div>
                    </div>
                    {% if request.user.is_authenticated %}

                    <div class="myaccount-content">
                        <div class="myaccount-upper">
                            <div class="account-user">
                                <div class="account-user-int">
                                    <p>{{ user.first_name.0 }} {{ user.last_name.0 }}</p>
                                </div>

                                <div class="account-user-details">
                                    <div class="account-name">
                                        <p>{{ user.first_name }} {{ user.last_name }}</p>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="17"
                                            viewBox="0 0 16 17" fill="none">
                                            <path fill-rule="evenodd" clip-rule="evenodd"
                                                d="M5.01371 3.26406C5.52816 3.22301 6.01655 3.02071 6.40936 2.68597C7.326 1.90481 8.67419 1.90481 9.59084 2.68597C9.98364 3.02071 10.472 3.22301 10.9865 3.26406C12.187 3.35987 13.1403 4.31318 13.2361 5.51371C13.2772 6.02816 13.4795 6.51655 13.8142 6.90936C14.5954 7.826 14.5954 9.17419 13.8142 10.0908C13.4795 10.4836 13.2772 10.972 13.2361 11.4865C13.1403 12.687 12.187 13.6403 10.9865 13.7361C10.472 13.7772 9.98364 13.9795 9.59084 14.3142C8.67419 15.0954 7.326 15.0954 6.40936 14.3142C6.01655 13.9795 5.52816 13.7772 5.01371 13.7361C3.81318 13.6403 2.85987 12.687 2.76406 11.4865C2.72301 10.972 2.52071 10.4836 2.18597 10.0908C1.40481 9.17419 1.40481 7.826 2.18597 6.90936C2.52071 6.51655 2.72301 6.02816 2.76406 5.51371C2.85987 4.31318 3.81318 3.35987 5.01371 3.26406ZM10.9658 7.46578C11.2782 7.15336 11.2782 6.64683 10.9658 6.33441C10.6534 6.02199 10.1468 6.02199 9.83441 6.33441L7.2001 8.96873L6.16578 7.93441C5.85336 7.62199 5.34683 7.62199 5.03441 7.93441C4.72199 8.24683 4.72199 8.75336 5.03441 9.06578L6.63441 10.6658C6.94683 10.9782 7.45336 10.9782 7.76578 10.6658L10.9658 7.46578Z"
                                                fill="#FCB810" />
                                        </svg>
                                    </div>

                                    <div class="account-email">
                                        <p>Email: <span>{{user.email}}</span></p>
                                    </div>

                                    <div class="account-phone">
                                        <p>Phone No: <span>{{ user.phone_number }}</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="account-button">
                                <div class="account-upper-button">
                                    <button><a href="{% url 'account:edit_user' id=user.id %}"> Edit Profile </a></button>
                                </div>
                                <div class="account-upper-button">
                                    <button><a href="{% url 'account:change_password'%}"> Change Password </a></button>
                                </div>
                            </div>
                        </div>

                        <div class="myaccount-lower">
                            <div class="account-user-heading">
                                <p>User Details</p>
                            </div>

                            <div class="personal-details">
                                <div class="personal-info">
                                    <p>Username</p>
                                    <h5>{{user.username}}</h5>
                                </div>
                                <div class="personal-info">
                                    <p>Role</p>
                                    <h5>{{ user.get_role_display }}</h5>
                                </div>
                                <div class="personal-info">
                                    <p>Department</p>
                                    <h5>{{ user.admin_category }}</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}

                </div>
            </div>
        </div>
</section>


{% include 'layouts/footer.html' %}